<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Surah;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['name' => 'الفاتحة', 'number' => 1, 'ayahs_count' => 7],
            ['name' => 'البقرة', 'number' => 2, 'ayahs_count' => 286],
            ['name' => 'آل عمران', 'number' => 3, 'ayahs_count' => 200],
            ['name' => 'النساء', 'number' => 4, 'ayahs_count' => 176],
            ['name' => 'المائدة', 'number' => 5, 'ayahs_count' => 120],
            ['name' => 'الأنعام', 'number' => 6, 'ayahs_count' => 165],
            ['name' => 'الأعراف', 'number' => 7, 'ayahs_count' => 206],
            ['name' => 'الأنفال', 'number' => 8, 'ayahs_count' => 75],
            ['name' => 'التوبة', 'number' => 9, 'ayahs_count' => 129],
            ['name' => 'يونس', 'number' => 10, 'ayahs_count' => 109],
            ['name' => 'هود', 'number' => 11, 'ayahs_count' => 123],
            ['name' => 'يوسف', 'number' => 12, 'ayahs_count' => 111],
            ['name' => 'الرعد', 'number' => 13, 'ayahs_count' => 43],
            ['name' => 'إبراهيم', 'number' => 14, 'ayahs_count' => 52],
            ['name' => 'الحجر', 'number' => 15, 'ayahs_count' => 99],
            ['name' => 'النحل', 'number' => 16, 'ayahs_count' => 128],
            ['name' => 'الإسراء', 'number' => 17, 'ayahs_count' => 111],
            ['name' => 'الكهف', 'number' => 18, 'ayahs_count' => 110],
            ['name' => 'مريم', 'number' => 19, 'ayahs_count' => 98],
            ['name' => 'طه', 'number' => 20, 'ayahs_count' => 135],
            ['name' => 'الأنبياء', 'number' => 21, 'ayahs_count' => 112],
            ['name' => 'الحج', 'number' => 22, 'ayahs_count' => 78],
            ['name' => 'المؤمنون', 'number' => 23, 'ayahs_count' => 118],
            ['name' => 'النور', 'number' => 24, 'ayahs_count' => 64],
            ['name' => 'الفرقان', 'number' => 25, 'ayahs_count' => 77],
            ['name' => 'الشعراء', 'number' => 26, 'ayahs_count' => 227],
            ['name' => 'النمل', 'number' => 27, 'ayahs_count' => 93],
            ['name' => 'القصص', 'number' => 28, 'ayahs_count' => 88],
            ['name' => 'العنكبوت', 'number' => 29, 'ayahs_count' => 69],
            ['name' => 'الروم', 'number' => 30, 'ayahs_count' => 60],
            ['name' => 'لقمان', 'number' => 31, 'ayahs_count' => 34],
            ['name' => 'السجدة', 'number' => 32, 'ayahs_count' => 30],
            ['name' => 'الأحزاب', 'number' => 33, 'ayahs_count' => 73],
            ['name' => 'سبأ', 'number' => 34, 'ayahs_count' => 54],
            ['name' => 'فاطر', 'number' => 35, 'ayahs_count' => 45],
            ['name' => 'يس', 'number' => 36, 'ayahs_count' => 83],
            ['name' => 'الصافات', 'number' => 37, 'ayahs_count' => 182],
            ['name' => 'ص', 'number' => 38, 'ayahs_count' => 88],
            ['name' => 'الزمر', 'number' => 39, 'ayahs_count' => 75],
            ['name' => 'غافر', 'number' => 40, 'ayahs_count' => 85],
            ['name' => 'فصلت', 'number' => 41, 'ayahs_count' => 54],
            ['name' => 'الشورى', 'number' => 42, 'ayahs_count' => 53],
            ['name' => 'الزخرف', 'number' => 43, 'ayahs_count' => 89],
            ['name' => 'الدخان', 'number' => 44, 'ayahs_count' => 59],
            ['name' => 'الجاثية', 'number' => 45, 'ayahs_count' => 37],
            ['name' => 'الأحقاف', 'number' => 46, 'ayahs_count' => 35],
            ['name' => 'محمد', 'number' => 47, 'ayahs_count' => 38],
            ['name' => 'الفتح', 'number' => 48, 'ayahs_count' => 29],
            ['name' => 'الحجرات', 'number' => 49, 'ayahs_count' => 18],
            ['name' => 'ق', 'number' => 50, 'ayahs_count' => 45],
            ['name' => 'الذاريات', 'number' => 51, 'ayahs_count' => 60],
            ['name' => 'الطور', 'number' => 52, 'ayahs_count' => 49],
            ['name' => 'النجم', 'number' => 53, 'ayahs_count' => 62],
            ['name' => 'القمر', 'number' => 54, 'ayahs_count' => 55],
            ['name' => 'الرحمن', 'number' => 55, 'ayahs_count' => 78],
            ['name' => 'الواقعة', 'number' => 56, 'ayahs_count' => 96],
            ['name' => 'الحديد', 'number' => 57, 'ayahs_count' => 29],
            ['name' => 'المجادلة', 'number' => 58, 'ayahs_count' => 22],
            ['name' => 'الحشر', 'number' => 59, 'ayahs_count' => 24],
            ['name' => 'الممتحنة', 'number' => 60, 'ayahs_count' => 13],
            ['name' => 'الصف', 'number' => 61, 'ayahs_count' => 14],
            ['name' => 'الجمعة', 'number' => 62, 'ayahs_count' => 11],
            ['name' => 'المنافقون', 'number' => 63, 'ayahs_count' => 11],
            ['name' => 'التغابن', 'number' => 64, 'ayahs_count' => 18],
            ['name' => 'الطلاق', 'number' => 65, 'ayahs_count' => 12],
            ['name' => 'التحريم', 'number' => 66, 'ayahs_count' => 12],
            ['name' => 'الملك', 'number' => 67, 'ayahs_count' => 30],
            ['name' => 'القلم', 'number' => 68, 'ayahs_count' => 52],
            ['name' => 'الحاقة', 'number' => 69, 'ayahs_count' => 52],
            ['name' => 'المعارج', 'number' => 70, 'ayahs_count' => 44],
            ['name' => 'نوح', 'number' => 71, 'ayahs_count' => 28],
            ['name' => 'الجن', 'number' => 72, 'ayahs_count' => 28],
            ['name' => 'المزمل', 'number' => 73, 'ayahs_count' => 20],
            ['name' => 'المدثر', 'number' => 74, 'ayahs_count' => 56],
            ['name' => 'القيامة', 'number' => 75, 'ayahs_count' => 40],
            ['name' => 'الإنسان', 'number' => 76, 'ayahs_count' => 31],
            ['name' => 'المرسلات', 'number' => 77, 'ayahs_count' => 50],
            ['name' => 'النبأ', 'number' => 78, 'ayahs_count' => 40],
            ['name' => 'النازعات', 'number' => 79, 'ayahs_count' => 46],
            ['name' => 'عبس', 'number' => 80, 'ayahs_count' => 42],
            ['name' => 'التكوير', 'number' => 81, 'ayahs_count' => 29],
            ['name' => 'الانفطار', 'number' => 82, 'ayahs_count' => 19],
            ['name' => 'المطففين', 'number' => 83, 'ayahs_count' => 36],
            ['name' => 'الانشقاق', 'number' => 84, 'ayahs_count' => 25],
            ['name' => 'البروج', 'number' => 85, 'ayahs_count' => 22],
            ['name' => 'الطارق', 'number' => 86, 'ayahs_count' => 17],
            ['name' => 'الأعلى', 'number' => 87, 'ayahs_count' => 19],
            ['name' => 'الغاشية', 'number' => 88, 'ayahs_count' => 26],
            ['name' => 'الفجر', 'number' => 89, 'ayahs_count' => 30],
            ['name' => 'البلد', 'number' => 90, 'ayahs_count' => 20],
            ['name' => 'الشمس', 'number' => 91, 'ayahs_count' => 15],
            ['name' => 'الليل', 'number' => 92, 'ayahs_count' => 21],
            ['name' => 'الضحى', 'number' => 93, 'ayahs_count' => 11],
            ['name' => 'الشرح', 'number' => 94, 'ayahs_count' => 8],
            ['name' => 'التين', 'number' => 95, 'ayahs_count' => 8],
            ['name' => 'العلق', 'number' => 96, 'ayahs_count' => 19],
            ['name' => 'القدر', 'number' => 97, 'ayahs_count' => 5],
            ['name' => 'البينة', 'number' => 98, 'ayahs_count' => 8],
            ['name' => 'الزلزلة', 'number' => 99, 'ayahs_count' => 8],
            ['name' => 'العاديات', 'number' => 100, 'ayahs_count' => 11],
            ['name' => 'القارعة', 'number' => 101, 'ayahs_count' => 11],
            ['name' => 'التكاثر', 'number' => 102, 'ayahs_count' => 8],
            ['name' => 'العصر', 'number' => 103, 'ayahs_count' => 3],
            ['name' => 'الهمزة', 'number' => 104, 'ayahs_count' => 9],
            ['name' => 'الفيل', 'number' => 105, 'ayahs_count' => 5],
            ['name' => 'قريش', 'number' => 106, 'ayahs_count' => 4],
            ['name' => 'الماعون', 'number' => 107, 'ayahs_count' => 7],
            ['name' => 'الكوثر', 'number' => 108, 'ayahs_count' => 3],
            ['name' => 'الكافرون', 'number' => 109, 'ayahs_count' => 6],
            ['name' => 'النصر', 'number' => 110, 'ayahs_count' => 3],
            ['name' => 'المسد', 'number' => 111, 'ayahs_count' => 5],
            ['name' => 'الإخلاص', 'number' => 112, 'ayahs_count' => 4],
            ['name' => 'الفلق', 'number' => 113, 'ayahs_count' => 5],
            ['name' => 'الناس', 'number' => 114, 'ayahs_count' => 6],
        ];

        // ✅ upsert: إذا موجود رقم السورة يحدثه، إذا غير موجود يضيفه
        Surah::upsert($surahs, ['number'], ['name', 'ayahs_count']);
    }
}
